### ISSUE TITLE
Icon pack

### ISSUE THREAD

**Issue by andrecbarros** [sixsixfive/Monotone#5]
Hi Sixsixfive,

I'm finishing an icon theme that mixes KDE oxygen, Gnome and self made detailed icons in a pack that include hicolor icons for sizes >= 32 pixels and symbolic icons for icons <= 24 pixels. Some of your icons match perfectly well with the small icons I plan to publish.

I know that the license allows it (when honoring it, of course) but I would first ask you if it is OK to you to "steal" some of your icons. Is it?

Regards,
André

**Comment by sixsixfive** [comment]
as long you follow the known terms:
https://creativecommons.org/licenses/by-sa/4.0/ - go ahead! (=

**Comment by andrecbarros** [comment]
Thanks man! Will let you know when I download the pack to github, may be, it will help you a little.

Best regards,
André
