### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by Minda1975** [sixsixfive/Monotone#6]
Hello. First of all I would like to thank you for the wonderful work. I have one passion. If possible, I would ask you to correct a couple of mistakes. The first is missing icon for ebook reader-Fbreader. Second, icon for alsamixergui is missing. Here links to screenshots:
https://s20.postimg.org/rxwispwj1/screenshot_20180127_172342.png
https://s20.postimg.org/fw14yl2q5/screenshot_20180127_172348.png

Thank you a lot.

**Comment by sixsixfive** [comment]
ok i have added a fbreader icon, however the alsamixergui icon is hardcoded in the desktop file(at least here on debian)

```
ssf@debian:~$ cat /usr/share/applications/alsamixergui.desktop
[Desktop Entry]
Name=Alsamixergui
Comment=Graphical audio mixer
Exec=/usr/bin/alsamixergui
Icon=/usr/share/pixmaps/alsamixergui.xpm
Terminal=false
Type=Application
Categories=AudioVideo;
```

**Comment by Minda1975** [comment]
Thanks, Sixsixfive. Icon for Fbreader now looks as it should. I guess I'll go around without icon for Alsamixergui. Thank you again for the work done.
