### ISSUE TITLE
build.sh failure

### ISSUE THREAD

**Issue by openmindead** [sixsixfive/Monotone#7]
Hi sixsixfive,
Thank you for your wonderful work.
I would never encounter this bug if I used dark themes, "unfortunately", I prefer bright ones. So long story short, here's what I get when running build.sh:

> creating 16px icons for KDE
Error reading SVG:Error domain 1 code 4 on line 1 column 1 of data: Start tag expected, '<' not found

As I understand this is svg-related thing. Could you please check if it works in your Debian environment?

**Comment by sixsixfive** [comment]
It works(I rebuild the theme on every commit), Do you use an non-GNU environment(BSD sed .etc) or an alternative shell?(its only tested under dash and bash)

**Comment by openmindead** [comment]
Hm, this is interesting. I tried this under Manjaro Linux 17.1.4 - stable branch. No luck with KDE Neon and Ubuntu live media as well - however, live session seems to have its own constraints. My shell is bash.
I'll try once more with Fedora, but ATM it looks very strange.

**Comment by openmindead** [comment]
OK it worked in Fedora 27 live media, I managed to apply colours I needed. I suspect librsvg to be responsible for this. My currently installed version is 2.42.2

BTW here are some missing icons for quite handy apps which may be important for many people:
Kate
Google Play Music Desktop Player (gpmdp)
Krita
Teamviewer
KGet
Telegram
qt-recordmyDesktop
Kdenlive
Kiten
nvidia-settings
Timeshift

This is not a feature request but maybe you are planning to add new icons in next releases, so these are quite good candidates.

**Comment by sixsixfive** [comment]
>I suspect librsvg to be responsible for this.

maybe, since its maintained by the GNOME developers which are widely known for breaking their stuff

@the icons 

sure i will add them in the future (also some of the icons are already included but hard coded at some distros(nvidia, telegram)

I guess its fixed then, so i close this now
